name: saku_digital
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  provider: ^6.0.3
  animated_text_kit: ^4.2.2
  flutter_animated_icons: ^1.0.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/bri_logo.png
    - assets/mandiri_logo.jpg
    - assets/bni_logo.png
    - assets/bca_logo.jpg
